databases:
  - name: BlueSquareAviationTech
    plan: free
    databaseName: concordnet_master
    user: concordnet_servant

services:
  - type: web
    plan: free
    name: BlueSquareAviation
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn concordnet.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: BlueSquareAviationTech
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4